### ISSUE TITLE
snowflake.connector.errors.ProgrammingError when running monitors

### ISSUE THREAD

**Issue by iporollo** [monosidev/monosi#22]
## Description

When running a monitor on Snowflake sample data, this error is encountered: 

```
Table Health Monitor: SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.lineitem

Finished in 0.52 seconds (SQL results took 0.52 seconds to load)
0 metrics, 0 failures

Traceback (most recent call last):
  File "/usr/local/bin/monosi", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/monosi/__main__.py", line 6, in main
    parser.parse(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/monosi/cli.py", line 32, in parse
    getattr(self, args.command)(argv[1:])
  File "/usr/local/lib/python3.9/site-packages/monosi/cli.py", line 59, in run
    task.run()
  File "/usr/local/lib/python3.9/site-packages/monosi/tasks/base.py", line 53, in run
    return self._process_tasks()
  File "/usr/local/lib/python3.9/site-packages/monosi/tasks/run.py", line 21, in _process_tasks
    results = [task.run() for task in self.task_queue]
  File "/usr/local/lib/python3.9/site-packages/monosi/tasks/run.py", line 21, in <listcomp>
    results = [task.run() for task in self.task_queue]
  File "/usr/local/lib/python3.9/site-packages/monosi/tasks/run.py", line 11, in run
    runner.run()
  File "/usr/local/lib/python3.9/site-packages/monosi/runner.py", line 49, in run
    results = self.execute(sql_stmt)
  File "/usr/local/lib/python3.9/site-packages/monosi/runner.py", line 34, in execute
    results = self.driver.execute_sql(sql)
  File "/usr/local/lib/python3.9/site-packages/monosi/drivers/snowflake/configuration.py", line 145, in execute_sql
    cs.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/cursor.py", line 790, in execute
    Error.errorhandler_wrapper(
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 272, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 327, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.9/site-packages/snowflake/connector/errors.py", line 206, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): SQL compilation error: error line 7 at position 23
invalid identifier 'I_CLASS'
```

## Steps to reproduce

1. Set up monosi project with the source database as `SNOWFLAKE_SAMPLE_DATA`
2. ~Run `monosi profile` to bootstrap the sample data monitors~
Create the following monitor
```
monosi:
  monitors:
  - table: SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.lineitem
    timestamp_field: l_commitdate
    type: table
```
3. Run `monosi run` to run the monitors
4. Notice that the error appears

## Other notes

~I believe this is happening with the `SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.item` table~

This is happening with the `SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.lineitem` table

**Comment by unkrich** [comment]
@iporollo Are you still experiencing this issue with the v0.0.2.post4 release?

**Comment by iporollo** [comment]
Yep still seeing it

**Comment by unkrich** [comment]
This issue occurs when the database and schema in your configuration file are not matching the database and schema of the table that is being monitored.

In the future, we should require that issue reports include the configuration files for the project and the sources where possible.

For now, no action, noting to put a better error raise in the code.
